window.esdocSearchIndex = [
  [
    "nvm-test/src/api/hooks.js~hooks",
    "class/src/api/hooks.js~Hooks.html",
    "<span>Hooks</span> <span class=\"search-result-import-path\">nvm-test/src/api/hooks.js</span>",
    "class"
  ],
  [
    "nvm-test/src/api/config.js~config",
    "variable/index.html#static-variable-config",
    "<span>config</span> <span class=\"search-result-import-path\">nvm-test/src/api/config.js</span>",
    "variable"
  ],
  [
    "nvm-test/src/api/nvm.js~exists",
    "function/index.html#static-function-exists",
    "<span>exists</span> <span class=\"search-result-import-path\">nvm-test/src/api/nvm.js</span>",
    "function"
  ],
  [
    "nvm-test/src/api/hooks.js~hookable",
    "function/index.html#static-function-hookable",
    "<span>hookable</span> <span class=\"search-result-import-path\">nvm-test/src/api/hooks.js</span>",
    "function"
  ],
  [
    "nvm-test/src/api/nvm.js~nvm",
    "function/index.html#static-function-nvm",
    "<span>nvm</span> <span class=\"search-result-import-path\">nvm-test/src/api/nvm.js</span>",
    "function"
  ],
  [
    "nvm-test/src/api/nvm-install.js~nvminstall",
    "function/index.html#static-function-nvmInstall",
    "<span>nvmInstall</span> <span class=\"search-result-import-path\">nvm-test/src/api/nvm-install.js</span>",
    "function"
  ],
  [
    "nvm-test/src/api/nvm-test.js~nvmtest",
    "function/index.html#static-function-nvmTest",
    "<span>nvmTest</span> <span class=\"search-result-import-path\">nvm-test/src/api/nvm-test.js</span>",
    "function"
  ],
  [
    "nvm-test/src/api/nvm-test-version.js~nvmtestversion",
    "function/index.html#static-function-nvmTestVersion",
    "<span>nvmTestVersion</span> <span class=\"search-result-import-path\">nvm-test/src/api/nvm-test-version.js</span>",
    "function"
  ],
  [
    "nvm-test/src/api/nvm-test-versions.js~nvmtestversions",
    "function/index.html#static-function-nvmTestVersions",
    "<span>nvmTestVersions</span> <span class=\"search-result-import-path\">nvm-test/src/api/nvm-test-versions.js</span>",
    "function"
  ],
  [
    "nvm-test/src/api/nvm.js~shell",
    "function/index.html#static-function-shell",
    "<span>shell</span> <span class=\"search-result-import-path\">nvm-test/src/api/nvm.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "* *,*",
    "test-file/test/api/01-hooks.spec.js.html#lineNumber10",
    "Hooks",
    "test"
  ],
  [
    "",
    "test-file/test/api/01-hooks.spec.js.html#lineNumber11",
    "Hooks should be call for new instance only",
    "test"
  ],
  [
    "",
    "test-file/test/api/01-hooks.spec.js.html#lineNumber16",
    "Hooks should have passed in properties",
    "test"
  ],
  [
    "* *,*",
    "test-file/test/api/00-index.spec.js.html#lineNumber6",
    "api",
    "test"
  ],
  [
    "",
    "test-file/test/api/00-index.spec.js.html#lineNumber7",
    "api sould fail to require if nvm does not exists",
    "test"
  ],
  [
    "* *,*",
    "test-file/test/api/02-nvm.spec.js.html#lineNumber12",
    "exists",
    "test"
  ],
  [
    "",
    "test-file/test/api/02-nvm.spec.js.html#lineNumber13",
    "exists should be a function",
    "test"
  ],
  [
    "",
    "test-file/test/api/02-nvm.spec.js.html#lineNumber17",
    "exists should return false if nvm does not exists",
    "test"
  ],
  [
    "",
    "test-file/test/api/02-nvm.spec.js.html#lineNumber26",
    "exists should return true if nvm exists",
    "test"
  ],
  [
    "* *,*",
    "test-file/test/api/01-hooks.spec.js.html#lineNumber25",
    "hookable",
    "test"
  ],
  [
    "",
    "test-file/test/api/01-hooks.spec.js.html#lineNumber26",
    "hookable should be a function",
    "test"
  ],
  [
    "",
    "test-file/test/api/01-hooks.spec.js.html#lineNumber61",
    "hookable should execute a \"post\" hook",
    "test"
  ],
  [
    "",
    "test-file/test/api/01-hooks.spec.js.html#lineNumber48",
    "hookable should execute a \"pre\" hook",
    "test"
  ],
  [
    "",
    "test-file/test/api/01-hooks.spec.js.html#lineNumber75",
    "hookable should reject and execute an \"error\" hook on Error",
    "test"
  ],
  [
    "",
    "test-file/test/api/01-hooks.spec.js.html#lineNumber38",
    "hookable should return a Promise (2nd level)",
    "test"
  ],
  [
    "",
    "test-file/test/api/01-hooks.spec.js.html#lineNumber34",
    "hookable should return a function (1st level)",
    "test"
  ],
  [
    "",
    "test-file/test/api/01-hooks.spec.js.html#lineNumber30",
    "hookable should throw a TypeError if argument is not a function",
    "test"
  ],
  [
    "* *,*",
    "test-file/test/api/02-nvm.spec.js.html#lineNumber49",
    "nvm",
    "test"
  ],
  [
    "",
    "test-file/test/api/02-nvm.spec.js.html#lineNumber50",
    "nvm should be a function",
    "test"
  ],
  [
    "",
    "test-file/test/api/02-nvm.spec.js.html#lineNumber54",
    "nvm should reject the Promise on Error",
    "test"
  ],
  [
    "",
    "test-file/test/api/02-nvm.spec.js.html#lineNumber58",
    "nvm should return and resolve the Promise",
    "test"
  ],
  [
    "* *,*",
    "test-file/test/api/03-nvm-install.spec.js.html#lineNumber7",
    "nvmInstall",
    "test"
  ],
  [
    "",
    "test-file/test/api/03-nvm-install.spec.js.html#lineNumber8",
    "nvmInstall should be a function",
    "test"
  ],
  [
    "",
    "test-file/test/api/03-nvm-install.spec.js.html#lineNumber34",
    "nvmInstall should execute an other install command",
    "test"
  ],
  [
    "",
    "test-file/test/api/03-nvm-install.spec.js.html#lineNumber26",
    "nvmInstall should reject with an invalid Node version",
    "test"
  ],
  [
    "",
    "test-file/test/api/03-nvm-install.spec.js.html#lineNumber12",
    "nvmInstall should reject with no Node version",
    "test"
  ],
  [
    "",
    "test-file/test/api/03-nvm-install.spec.js.html#lineNumber30",
    "nvmInstall should resolve with a valid Node version",
    "test"
  ],
  [
    "* *,*",
    "test-file/test/api/04-nvm-test.spec.js.html#lineNumber7",
    "nvmTest",
    "test"
  ],
  [
    "",
    "test-file/test/api/04-nvm-test.spec.js.html#lineNumber8",
    "nvmTest should be a function",
    "test"
  ],
  [
    "",
    "test-file/test/api/04-nvm-test.spec.js.html#lineNumber25",
    "nvmTest should execute an other test command",
    "test"
  ],
  [
    "",
    "test-file/test/api/04-nvm-test.spec.js.html#lineNumber16",
    "nvmTest should reject with an invalid Node version",
    "test"
  ],
  [
    "",
    "test-file/test/api/04-nvm-test.spec.js.html#lineNumber12",
    "nvmTest should reject with no Node version",
    "test"
  ],
  [
    "",
    "test-file/test/api/04-nvm-test.spec.js.html#lineNumber20",
    "nvmTest should resolve with a valid Node version",
    "test"
  ],
  [
    "* *,*",
    "test-file/test/api/05-nvm-test-version.spec.js.html#lineNumber7",
    "nvmTestVersion",
    "test"
  ],
  [
    "",
    "test-file/test/api/05-nvm-test-version.spec.js.html#lineNumber8",
    "nvmTestVersion should be a function",
    "test"
  ],
  [
    "",
    "test-file/test/api/05-nvm-test-version.spec.js.html#lineNumber21",
    "nvmTestVersion should execute others install and test commands",
    "test"
  ],
  [
    "",
    "test-file/test/api/05-nvm-test-version.spec.js.html#lineNumber12",
    "nvmTestVersion should reject with no Node version",
    "test"
  ],
  [
    "",
    "test-file/test/api/05-nvm-test-version.spec.js.html#lineNumber16",
    "nvmTestVersion should resolve with a valid Node version",
    "test"
  ],
  [
    "* *,*",
    "test-file/test/api/06-nvm-test-versions.spec.js.html#lineNumber7",
    "nvmTestVersions",
    "test"
  ],
  [
    "",
    "test-file/test/api/06-nvm-test-versions.spec.js.html#lineNumber8",
    "nvmTestVersions should be a function",
    "test"
  ],
  [
    "",
    "test-file/test/api/06-nvm-test-versions.spec.js.html#lineNumber39",
    "nvmTestVersions should execute others install and test commands",
    "test"
  ],
  [
    "",
    "test-file/test/api/06-nvm-test-versions.spec.js.html#lineNumber34",
    "nvmTestVersions should resolve with a valid Node version",
    "test"
  ],
  [
    "",
    "test-file/test/api/06-nvm-test-versions.spec.js.html#lineNumber23",
    "nvmTestVersions should return error code with an invalid Node version",
    "test"
  ],
  [
    "",
    "test-file/test/api/06-nvm-test-versions.spec.js.html#lineNumber12",
    "nvmTestVersions should return error code with no Node version",
    "test"
  ],
  [
    "* *,*",
    "test-file/test/api/02-nvm.spec.js.html#lineNumber32",
    "shell",
    "test"
  ],
  [
    "",
    "test-file/test/api/02-nvm.spec.js.html#lineNumber33",
    "shell should be a function",
    "test"
  ],
  [
    "",
    "test-file/test/api/02-nvm.spec.js.html#lineNumber42",
    "shell should execute with success",
    "test"
  ],
  [
    "",
    "test-file/test/api/02-nvm.spec.js.html#lineNumber37",
    "shell should return a ChildProcess",
    "test"
  ],
  [
    "src/api.js",
    "file/src/api.js.html",
    "src/api.js",
    "file"
  ],
  [
    "src/api/config.js",
    "file/src/api/config.js.html",
    "src/api/config.js",
    "file"
  ],
  [
    "src/api/config.js~command",
    "typedef/index.html#static-typedef-command",
    "src/api/config.js~command",
    "typedef"
  ],
  [
    "src/api/config.js~version",
    "typedef/index.html#static-typedef-version",
    "src/api/config.js~version",
    "typedef"
  ],
  [
    "src/api/hooks.js",
    "file/src/api/hooks.js.html",
    "src/api/hooks.js",
    "file"
  ],
  [
    "src/api/hooks.js~hook",
    "typedef/index.html#static-typedef-Hook",
    "src/api/hooks.js~Hook",
    "typedef"
  ],
  [
    "src/api/hooks.js~hookable",
    "typedef/index.html#static-typedef-Hookable",
    "src/api/hooks.js~Hookable",
    "typedef"
  ],
  [
    "src/api/hooks.js~hooks#constructor",
    "class/src/api/hooks.js~Hooks.html#instance-constructor-constructor",
    "src/api/hooks.js~Hooks#constructor",
    "method"
  ],
  [
    "src/api/index.js",
    "file/src/api/index.js.html",
    "src/api/index.js",
    "file"
  ],
  [
    "src/api/nvm-install.js",
    "file/src/api/nvm-install.js.html",
    "src/api/nvm-install.js",
    "file"
  ],
  [
    "src/api/nvm-test-version.js",
    "file/src/api/nvm-test-version.js.html",
    "src/api/nvm-test-version.js",
    "file"
  ],
  [
    "src/api/nvm-test-versions.js",
    "file/src/api/nvm-test-versions.js.html",
    "src/api/nvm-test-versions.js",
    "file"
  ],
  [
    "src/api/nvm-test.js",
    "file/src/api/nvm-test.js.html",
    "src/api/nvm-test.js",
    "file"
  ],
  [
    "src/api/nvm.js",
    "file/src/api/nvm.js.html",
    "src/api/nvm.js",
    "file"
  ],
  [
    "src/bin.js",
    "file/src/bin.js.html",
    "src/bin.js",
    "file"
  ],
  [
    "src/command.js",
    "file/src/command.js.html",
    "src/command.js",
    "file"
  ],
  [
    "src/utils.js",
    "file/src/utils.js.html",
    "src/utils.js",
    "file"
  ],
  [
    "test/api/00-index.spec.js",
    "test-file/test/api/00-index.spec.js.html",
    "test/api/00-index.spec.js",
    "testFile"
  ],
  [
    "test/api/01-hooks.spec.js",
    "test-file/test/api/01-hooks.spec.js.html",
    "test/api/01-hooks.spec.js",
    "testFile"
  ],
  [
    "test/api/02-nvm.spec.js",
    "test-file/test/api/02-nvm.spec.js.html",
    "test/api/02-nvm.spec.js",
    "testFile"
  ],
  [
    "test/api/03-nvm-install.spec.js",
    "test-file/test/api/03-nvm-install.spec.js.html",
    "test/api/03-nvm-install.spec.js",
    "testFile"
  ],
  [
    "test/api/04-nvm-test.spec.js",
    "test-file/test/api/04-nvm-test.spec.js.html",
    "test/api/04-nvm-test.spec.js",
    "testFile"
  ],
  [
    "test/api/05-nvm-test-version.spec.js",
    "test-file/test/api/05-nvm-test-version.spec.js.html",
    "test/api/05-nvm-test-version.spec.js",
    "testFile"
  ],
  [
    "test/api/06-nvm-test-versions.spec.js",
    "test-file/test/api/06-nvm-test-versions.spec.js.html",
    "test/api/06-nvm-test-versions.spec.js",
    "testFile"
  ]
]